test:
  script:
  - git submodule init
  - cd boost && ./bootstrap.sh
  - cd boost && ./b2 address-model=64
  - mkdir build
  - cd build && cmake -DBOOST_ROOT=$PWD/../boost ..
  - cd build && cmake --build .
