test:
  script:
  # Todo: Figure out how to run these commands without SSL errors in the Runner
  #- git submodule update --init --recursive
  #- mkdir build
  - cd boost
  - ./bootstrap.sh
  - ./b2 address-model=64
  - cd ..
  - mkdir build
  - cd build
  # windows:
  # cmake -DBOOST_ROOT=%CD%/../boost -DCMAKE_PREFIX_PATH=Q:\qt_official\5.9\msvc2017_64 -G "Visual Studio 15 2017 Win64" ..  
  - cmake -DBOOST_ROOT=$PWD/../boost ..
  - cmake --build .

