image: docker.david-forstenlechner.com/gitrunner_cpp

cache:
  paths:
    - boost/

test_linux:
  tags:
    - linux
  script:
    - cd boost
    - git submodule update --init --recursive
    - ./bootstrap.sh
    - ./b2 -j4 address-model=64
    - cd ..
    - mkdir build
    - cd build
    # Windows Visual Studio 2017:
    # cmake -DBOOST_ROOT=%CD%/../boost -DCMAKE_PREFIX_PATH=Q:\qt_official\5.9\msvc2017_64 -G "Visual Studio 15 2017 Win64" ..  
    # MacOS XCode:
    # cmake -DBOOST_ROOT=$PWD/../boost -DCMAKE_PREFIX_PATH=/Users/davidf/Qt/5.9/clang_64 -G "Xcode" .. 
    - cmake -DBOOST_ROOT=$PWD/../boost -DCMAKE_PREFIX_PATH=/usr/local/qt/5.9.0/64_dll ..
    - cmake --build .

test_macos:
  tags:
    - macos
  script:
    - git submodule update --init --recursive
    - cd boost
    - ./bootstrap.sh
    - ./b2 -j4 address-model=64
    - cd ..
    - mkdir build
    - cd build
    # Windows Visual Studio 2017:
    # cmake -DBOOST_ROOT=%CD%/../boost -DCMAKE_PREFIX_PATH=Q:\qt_official\5.9\msvc2017_64 -G "Visual Studio 15 2017 Win64" ..  
    # MacOS XCode:
    # cmake -DBOOST_ROOT=$PWD/../boost -DCMAKE_PREFIX_PATH=/Users/davidf/Qt/5.9/clang_64 -G "Xcode" .. 
    - cmake -DBOOST_ROOT=$PWD/../boost -DCMAKE_PREFIX_PATH=/Users/davidf/Qt/5.9/clang_64 ..
    - cmake --build .
