before_script:
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\""
  - cd boost
  - bootstrap.bat
  - b2 address-model=64
  - cd ..
  - mkdir build

cmake_build:
  script:
    - cd build
    - cmake -DBOOST_ROOT="D:\\branches\\sodium-cxx-examples\\boost" ..
    - cmake --build .
