before_script:
  - git submodule init
  - cd boost
  - ./bootstrap.sh
  - ./b2 address-model=64
  - cd ..
  - mkdir build

test:
  script:
  - cd build
  - cmake -DBOOST_ROOT=$PWD/boost ..
  - cmake --build .
