test:
  script:
  # Todo: Figure out how to run these commands without SSL errors in the Runner
  #- git submodule update --init --recursive
  #- mkdir build
  - cd boost
  - ./bootstrap.sh
  - ./b2 address-model=64
  - cd ../build 
  - cmake -DBOOST_ROOT=$PWD/../boost ..
  - cmake --build .
